namespace MicroMsg.Scene
{
    using System;

    public enum AddContactScene
    {
        MM_ADDSCENE_BIZ_CONFERENCE = 40,
        MM_ADDSCENE_BOTTLE = 0x19,
        MM_ADDSCENE_BRAND_QA = 0x22,
        MM_ADDSCENE_CHATROOM = 14,
        MM_ADDSCENE_CORP_EMAIL = 0x10,
        MM_ADDSCENE_FACEBOOK = 0x1f,
        MM_ADDSCENE_FUZZY_SEARCH = 0x23,
        MM_ADDSCENE_LBS = 0x12,
        MM_ADDSCENE_LOGO_WALL = 0x24,
        MM_ADDSCENE_PF_CONTACT = 6,
        MM_ADDSCENE_PF_EMAIL = 5,
        MM_ADDSCENE_PF_GROUP = 8,
        MM_ADDSCENE_PF_MOBILE = 10,
        MM_ADDSCENE_PF_MOBILE_EMAIL = 11,
        MM_ADDSCENE_PF_MOBILE_REVERSE = 0x15,
        MM_ADDSCENE_PF_QQ = 4,
        MM_ADDSCENE_PF_SHAKE_PHONE_GROUP = 0x17,
        MM_ADDSCENE_PF_SHAKE_PHONE_OPPSEX = 0x18,
        MM_ADDSCENE_PF_SHAKE_PHONE_PAIR = 0x16,
        MM_ADDSCENE_PF_UNKNOWN = 9,
        MM_ADDSCENE_PF_WEIXIN = 7,
        MM_ADDSCENE_PROMOTE_BIZCARD = 0x29,
        MM_ADDSCENE_PROMOTE_MSG = 0x26,
        MM_ADDSCENE_QRCode = 30,
        MM_ADDSCENE_SEARCH_BRAND = 0x27,
        MM_ADDSCENE_SEARCH_EMAIL = 2,
        MM_ADDSCENE_SEARCH_PHONE = 15,
        MM_ADDSCENE_SEARCH_QQ = 1,
        MM_ADDSCENE_SEARCH_WEIXIN = 3,
        MM_ADDSCENE_SEND_CARD = 0x11,
        MM_ADDSCENE_SHAKE_SCENE1 = 0x1a,
        MM_ADDSCENE_SHAKE_SCENE2 = 0x1b,
        MM_ADDSCENE_SHAKE_SCENE3 = 0x1c,
        MM_ADDSCENE_SHAKE_SCENE4 = 0x1d,
        MM_ADDSCENE_SNS = 0x20,
        MM_ADDSCENE_TIMELINE_BIZ = 0x25,
        MM_ADDSCENE_UNKNOW = 0,
        MM_ADDSCENE_VIEW_MOBILE = 13,
        MM_ADDSCENE_VIEW_QQ = 12,
        MM_ADDSCENE_WEB = 0x21
    }
}

