namespace MicroMsg.Scene
{
    using System;

    public enum GetA8KeyScene
    {
        MMGETA8KEY_SCENE_UNKNOW,
        MMGETA8KEY_SCENE_MSG,
        MMGETA8KEY_SCENE_TIMELINE,
        MMGETA8KEY_SCENE_PROFILE,
        MMGETA8KEY_SCENE_QRCODE,
        MMGETA8KEY_SCENE_QZONE,
        MMGETA8KEY_SCENE_OAUTH,
        MMGETA8KEY_SCENE_OPEN,
        MMGETA8KEY_SCENE_PLUGIN,
        MMGETA8KEY_SCENE_JUMPURL,
        MMGETA8KEY_SCENE_SHAKETV,
        MMGETA8KEY_SCENE_SCANBARCODE,
        MMGETA8KEY_SCENE_SCANIMAGE,
        MMGETA8KEY_SCENE_SCANSTREETVIEW,
        MMGETA8KEY_SCENE_FAV,
        MMGETA8KEY_SCENE_MMBIZ,
        MMGETA8KEY_SCENE_QQMAIL,
        MMGETA8KEY_SCENE_LINKEDIN,
        MMGETA8KEY_SCENE_SHAKETV_DETAIL,
        MMGETA8KEY_SCENE_BIZHOMEPAGE,
        MMGETA8KEY_SCENE_USBCONNECT,
        MMGETA8KEY_SCENE_SHORT_URL,
        MMGETA8KEY_SCENE_WIFI,
        MMGETA8KEY_SCENE_OUTSIDE_DEEPLINK,
        MMGETA8KEY_SCENE_PUSH_LOGIN_URL
    }
}
